/*
 * ddosmitigator API
 *
 * ddosmitigator API generated from ddosmitigator.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Stats struct {
	// Dropped Packets/s
	Pps int32 `json:"pps,omitempty"`
	// Total Dropped Packets
	Pkts int32 `json:"pkts,omitempty"`
}
