/*
 * ddosmitigator API
 *
 * ddosmitigator API generated from ddosmitigator.yang
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Ddosmitigator struct {
	// Name of the ddosmitigator service
	Name string `json:"name,omitempty"`
	// UUID of the Cube
	Uuid string `json:"uuid,omitempty"`
	// Type of the Cube (TC, XDP_SKB, XDP_DRV)
	Type_ string `json:"type,omitempty"`
	ServiceName string `json:"service-name,omitempty"`
	// Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
	Loglevel string `json:"loglevel,omitempty"`
	Stats *Stats `json:"stats,omitempty"`
	// Blacklisted source IP addresses
	BlacklistSrc []BlacklistSrc `json:"blacklist-src,omitempty"`
	// Blacklisted destination IP addresses
	BlacklistDst []BlacklistDst `json:"blacklist-dst,omitempty"`
}
